apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-ui
  namespace: mafia
  labels:
    name: mafia-ui
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-ui
        app: mafia
    spec:
      containers:
      - name: mafia-ui-container
        image: taleodor/mafia-vue@sha256:9aea18d6cd4800031003dbde857806e289c0ea960a5bdbd03ac6266cabfe3848
        env:
        - name: HUB_HOST
          value: mafia-backend-service.mafia
        - name: HUB_PORT
          value: "3000"
        ports:
        - containerPort: 80
