namespace: mafia
backend:
  image: <%PROJECT__f3a3a0c2-9850-4341-b3d7-0570c5007b46__master%>
  replicaCount: 1
  port: 3000
  targetPort: 3000
ui:
  image: <%PROJECT__a5bee672-016e-40c5-bbf1-06c54569b759__master%>
  replicaCount: 1
  port: 80
  targetPort: 80
ingress:
  nginxEnabled: false
  traefikEnabled: true
  host: mafia-staging.rhythm.relizahub.com