apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-ui
  namespace: mafia
  labels:
    name: mafia-ui
    app: mafia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mafia
  template:
    metadata:
      labels:
        name: mafia-ui
        app: mafia
    spec:
      containers:
      - name: mafia-ui-container
        image: taleodor/mafia-vue
        env:
        - name: HUB_HOST
          value: mafia-backend-service
        - name: HUB_PORT
          value: "3000"
        ports:
        - containerPort: 80
