on:
  repository_dispatch:
    types: [reliza-build-event]

name: Pull versions from Reliza and obtain k8s definitions if changed

# BUILD_ENV_PARAMS secret must be created in the format 
# --env TEST|k8s_test,--env PRODUCTION --instance fc87512a-983c-4127-8f5f-2f876a0f1b76 --namespace default|k8s_production
# (different variations are comma separaed, instance and namespace are optional, output directory follows vertical bar | separator)

# INDIRECTORY secret must be set to the directory containing base definitions, i.e. k8s_templates

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      BUILD_ENV_PARAMS: ${{ secrets.BUILD_ENV_PARAMS }}
      INDIRECTORY: ${{ secrets.INDIRECTORY }}
      RELIZA_API_ID: ${{ secrets.RELIZA_ORGANIZATION_API_ID }}
      RELIZA_API_KEY: ${{ secrets.RELIZA_ORGANIZATION_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
#      - name: Update definitions based on Reliza Hub data
#        run: |
#          IFS="," read -ra ENV_BUILDS <<< "$BUILD_ENV_PARAMS"
#          for envbuild in "${ENV_BUILDS[@]}"; do
#            # chmod 0777 $GITHUB_WORKSPACE/${SPLIT_BUILD_ENV[1]}
#            IFS="|" read -ra SPLIT_BUILD_ENV <<< "$envbuild"
#            docker run --rm -u root -v $GITHUB_WORKSPACE/$INDIRECTORY/:/indir -v $GITHUB_WORKSPACE/${SPLIT_BUILD_ENV[1]}/:/outdir relizaio/reliza-cli parsetemplate -i $RELIZA_API_ID -k $RELIZA_API_KEY ${SPLIT_BUILD_ENV[0]}
#          done
      - name: Update definitions based on Reliza Hub data
        run: |
          # test
          docker run --rm -v ${PWD}/k8s:/sourcek k8s.gcr.io/kustomize/kustomize:v4.1.3 build /sourcek/overlays/test > k8s_test_gcp/kustomized_defs.yaml
          docker run --rm -u root -v ${PWD}/k8s_test_gcp/kustomized_defs.yaml:/values.yaml -v ${PWD}/k8s_test_gcp:/output_dir relizaio/reliza-cli replacetags -i $RELIZA_API_ID -k $RELIZA_API_KEY --instanceuri testmafia.brolia.com --infile /values.yaml --outfile /output_dir/mafia_defs.yaml
          rm k8s_test_gcp/kustomized_defs.yaml
          
          # prod
          docker run --rm -v ${PWD}/k8s:/sourcek k8s.gcr.io/kustomize/kustomize:v4.1.3 build /sourcek/overlays/prod > k8s_prod_gcp/kustomized_defs.yaml
          docker run --rm -u root -v ${PWD}/k8s_prod_gcp/kustomized_defs.yaml:/values.yaml -v ${PWD}/k8s_prod_gcp:/output_dir relizaio/reliza-cli replacetags -i $RELIZA_API_ID -k $RELIZA_API_KEY --instanceuri mafia.brolia.com --infile /values.yaml --outfile /output_dir/mafia_defs.yaml
          rm k8s_prod_gcp/kustomized_defs.yaml
      - name: Check if the change happened and commit
        run: |
          cd $GITHUB_WORKSPACE
          git status
          lines=$(git status -s | wc -l)
          if [ $lines -gt 0 ];then
            echo "committing"
            git config --global user.name 'reliza-auto'
            git config --global user.email 'info@reliza.io'
            git add .
            git commit -m "fix: auto-update of deployment based on Reliza Hub details"
            git push
            commit_sha=$(git log -1 --pretty='%H')
            # Generate version and stream version to Reliza Hub
            # get version
            docker run --rm relizaio/reliza-cli getversion -k ${{ secrets.RELIZA_API_KEY }} -i ${{ secrets.RELIZA_API_ID }} -b $GITHUB_REF --metadata GitHub > full_version_output 2>&1
            # show reliza command output in case there is error
            cat full_version_output
            # now construct actual version - we could use jq, but why install another tool in CI env?
            cat full_version_output | grep version | cut -d ':' -f 2 | cut -d '"' -f 2 > version
            vvar=$(cat version)
            # Construct Reliza command to stream version to reliza
            echo -n "--artid github.com/$GITHUB_REPOSITORY " >> reliza_command
            echo -n "--artbuildid github$GITHUB_ACTION$commit_sha " >> reliza_command
            echo -n "--artbuilduri https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID " >> reliza_command
            echo -n "--artcimeta GitHub Actions " >> reliza_command
            echo -n "--arttype file " >> reliza_command
            echo -n "--artdigests sha1:$commit_sha " >> reliza_command
            echo -n "-b $GITHUB_REF --vcstype git --commit $commit_sha --commitmessage \"$(git log -1 --pretty='%s')\" \
              -k ${{ secrets.RELIZA_API_KEY }} -i ${{ secrets.RELIZA_API_ID }} --vcsuri github.com/$GITHUB_REPOSITORY \
              -v $vvar " >> reliza_command
            # prepare list of commits
            echo -n "--commits $(git log -1 --date=iso-strict --pretty='%H|||%ad|||%s' | base64 -w 0) " >> reliza_command
            cat reliza_command
            # send version to reliza
            echo docker run --rm relizaio/reliza-cli addrelease $(cat reliza_command) > rlz_cmd_exec
            eval $(cat rlz_cmd_exec)
          else
            echo "no change, nothing to commit"
          fi